In [36]:
import numpy as np
import matplotlib.pyplot as plt

In [37]:
%matplotlib inline
plt.style.use('seaborn-ticks')
plt.rcParams.update({'font.size': 14})

In [38]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],  # стаж репетитора
              [500, 700, 750, 600, 1450,        # средняя стоимость занятия
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]],  # квалификация репетитора
              dtype = np.float64).T 

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1]) # поступил или нет ученик на специальность Математика
X

array([[1.00e+00, 1.00e+00, 5.00e+02, 1.00e+00],
       [1.00e+00, 1.00e+00, 7.00e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 7.50e+02, 2.00e+00],
       [1.00e+00, 1.00e+00, 6.00e+02, 1.00e+00],
       [1.00e+00, 3.00e+00, 1.45e+03, 2.00e+00],
       [1.00e+00, 0.00e+00, 8.00e+02, 1.00e+00],
       [1.00e+00, 5.00e+00, 1.50e+03, 3.00e+00],
       [1.00e+00, 1.00e+01, 2.00e+03, 3.00e+00],
       [1.00e+00, 1.00e+00, 4.50e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 1.00e+03, 2.00e+00]])

In [39]:
def standard_scaler(x):
    res = (x - x.mean()) / x.std()
    return res

X_st = X.copy()
X_st[:, 2] = standard_scaler(X[:, 2])
X_st[:, 2]

array([-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
       -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735])

In [40]:
def sigmoid(x):
  return  1/(1+np.exp(-x))

In [41]:
# логистическая регрессия
def eval_LR_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    for i in range(1, iterations + 1):
        z = np.dot(X, w) # log(p/(1-p))
        y_pred = sigmoid(z) # p [0, 1]
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

In [61]:
#w = eval_LR_model(X_st, y, 2000, 1e-1)
w = eval_LR_model(X_st, y, 10000, 10)`# задание 2. Подобранные параметры

1000 [-66.16312453  -5.98180042 -18.47328021  53.11963154] 0.06843059019607386
2000 [-71.85202389  -6.35927791 -20.18324626  57.42889207] 0.06302517594534543
3000 [-77.05366198  -6.69385079 -21.7544236   61.34840071] 0.058522055242266
4000 [-81.87758043  -6.9978981  -23.21604637  64.97118242] 0.054657665251133115
5000 [-86.39089935  -7.27906729 -24.58592091  68.35426317] 0.051279115507307974
6000 [-90.63924013  -7.54197857 -25.8765906   71.53528669] 0.04828778085923328
7000 [-94.65599672  -7.78963182 -27.09752458  74.54107443] 0.04561479566655489
8000 [-98.46700439  -8.02411839 -28.25621991  77.39193612] 0.04320921188357686
9000 [-102.09307979   -8.24699022  -29.35881608   80.10397915] 0.0410317274748385
10000 [-105.5515018    -8.45945856  -30.41046576   82.69042412] 0.039051087920068436


In [62]:
y_pred = sigmoid(np.dot(X_st, w))
print(y_pred.round(2))
print(y)
print(np.where(y_pred > 0.5, 1, 0))

[0.18 0.   1.   0.   0.99 0.   1.   0.   0.83 1.  ]
[0 0 1 0 1 0 1 0 1 1]
[0 0 1 0 1 0 1 0 1 1]


In [44]:
def calc_logloss(y, y_pred):    
    #err = np.mean(- y * np.log(y_pred) - (1.0 - y) * np.log(1.0 - y_pred))
    # задание 1. Проверка на 0 под логарифмом
    err = np.mean(- y * np.log(np.where(y_pred == 0, 1e-10, y_pred )) - (1.0 - y) * np.log(np.where(1.0 - y_pred == 0, 1e-10, 1.0 - y_pred )))
    return err

In [63]:
calc_logloss(y, y_pred)

0.039049196910240745

In [66]:
# задание 3
def calc_pred_proba(X, w):
    result = sigmoid(np.dot(X, w))
    return result

In [68]:
print(calc_pred_proba(X_st, w).round(2))

[0.18 0.   1.   0.   0.99 0.   1.   0.   0.83 1.  ]


In [69]:
# задание 4
def calc_pred(X, w, delimeter):
    return np.where(calc_pred_proba(X, w) >= delimeter, 1, 0)    

In [72]:
print(calc_pred(X_st, w, 0.999).round(2))

[0 0 1 0 0 0 1 0 0 1]
